export const TotalTime = 5;

export const NoteColors: Record<string, string> = {
  "A": "var(--note-a)",
  "B": "var(--note-b)",
  "C": "var(--note-c)",
  "D": "var(--note-d)",
  "E": "var(--note-e)",
  "F": "var(--note-f)",
  "G": "var(--note-g)",

  "A#": "var(--note-a-sharp)",
  "C#": "var(--note-c-sharp)",
  "D#": "var(--note-d-sharp)",
  "F#": "var(--note-f-sharp)",
  "G#": "var(--note-g-sharp)",

  "Ab": "var(--note-a-flat)",
  "Bb": "var(--note-b-flat)",
  "Db": "var(--note-d-flat)",
  "Eb": "var(--note-e-flat)",
  "Gb": "var(--note-g-flat)",
};

export const StringNotes: Record<number, Record<string, Array<string>>> = {
  6: {
    //0:  ["E"],
    1:  ["F"],
    2:  ["F#", "Gb"],
    3:  ["G"],
    4:  ["G#", "Ab"],
    5:  ["A"],
    6:  ["A#", "Bb"],
    7:  ["B"],
    8:  ["C"],
    9:  ["C#", "Db"],
    10: ["D"],
    11: ["D#", "Eb"],
    12: ["E"],
  },

  5: {
    //0:  ["A"],
    1:  ["A#", "Bb"],
    2:  ["B"],
    3:  ["C"],
    4:  ["C#", "Db"],
    5:  ["D"],
    6:  ["D#", "Eb"],
    7:  ["E"],
    8:  ["F"],
    9:  ["F#", "Gb"],
    10: ["G"],
    11: ["G#", "Ab"],
    12: ["A"],
  },
  
  4: {
    //0:  ["D"],
    1:  ["D#", "Eb"],
    2:  ["E"],
    3:  ["F"],
    4:  ["F#", "Gb"],
    5:  ["G"],
    6:  ["G#", "Ab"],
    7:  ["A"],
    8:  ["A#", "Bb"],
    9:  ["B"],
    10: ["C"],
    11: ["C#", "Db"],
    12: ["D"],
  },

  3: {
    //0:  ["G"],
    1:  ["G#", "Ab"],
    2:  ["A"],
    3:  ["A#", "Bb"],
    4:  ["B"],
    5:  ["C"],
    6:  ["C#", "Db"],
    7:  ["D"],
    8:  ["D#", "Eb"],
    9: ["E"],
    10: ["F"],
    11: ["F#", "Gb"],
    12: ["G"],
  },

  2: {
    //0:  ["B"],
    1:  ["C"],
    2:  ["C#", "Db"],
    3: ["D"],
    4: ["D#", "Eb"],
    5: ["E"],
    6:  ["F"],
    7:  ["F#", "Gb"],
    8:  ["G"],
    9:  ["G#", "Ab"],
    10:  ["A"],
    11:  ["A#", "Bb"],
    12:  ["B"],
  },

  1: {
    //0:  ["E"],
    1:  ["F"],
    2:  ["F#", "Gb"],
    3:  ["G"],
    4:  ["G#", "Ab"],
    5:  ["A"],
    6:  ["A#", "Bb"],
    7:  ["B"],
    8:  ["C"],
    9:  ["C#", "Db"],
    10: ["D"],
    11: ["D#", "Eb"],
    12: ["E"],
  },
};
